config/routes.rb
Rails.application.routes.draw do
  root to: "patients#index"
  get 'home/index'
  devise_for :users
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  resources :patients #, except: [:destroy]
  #delete '/patients/:id/destroy', to:'patients#destroy', as:'delete_patient'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
    validates :firstname, :presence=>true
    validates :lastname, :presence=>true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    def logged_in?
        redirect_to users_new_url unless current_user.present?
    end
    protected
      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:is_doctor, :email, :password)}

          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:is_doctor, :email, :password, :current_password)}
      end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_url, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_url, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:firstname, :lastname, :mobile_no, :email, :address, :pincode, :appointment_date, :reference_no, :diseases, :special_remarks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_importmap_tags %>
  </head>
<style> 
body {
  font-family: Helvetica;
  margin: 0;
}
a {
  text-decoration: none;
  color: #000;
}
.site-header { 
  border-bottom: 1px solid #ccc;
  padding: .5em 1em;
}

.site-header::after {
  content: "";
  display: table;
  clear: both;
}

.site-identity {
  float: left;
}

.site-identity h1 {
  font-size: 1.5em;
  margin: .7em 0 .3em 0;
  display: inline-block;
}

.site-identity img {
  max-width: 123px;
  float: left;
  margin: 0 10px 0 0;
}

.site-navigation {
  float: right;
}

.site-navigation ul, li {
  margin: 0; 
  padding: 0;
}

.site-navigation li {
  display: inline-block;
  margin: 1.4em 1em 1em 1em;
}

</style>
  <body>

  <header class="site-header">
  <div class="site-identity">
    <a href="#"><img src="/assets/mainlogo.png" alt="Site Name" /></a>
    <h1><%= link_to "Helth Care", patients_path %></h1>
  </div>  
  <nav class="site-navigation">
    <ul class="nav">
      <li>
        <% if user_signed_in? %>
            Signed in as <text style="color:red;"><%= current_user.email %></text>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
            <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
        <% end %>
    </li> 
    </ul>
  </nav>
</header>

    <%= yield %>

    <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
      <div class="container text-center">
        <small>Copyright &copy; Helth Care</small>
      </div>
    </footer>

  </body>
</html>

app/views/patients/_form.html.erb
<div class="container bootstrap snippets bootdey">
  <div class="row ng-scope">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <div class="pv-lg">
            <img class="center-block img-responsive img-circle img-thumbnail thumb100" src="/assets/login-img.png" alt="Contact" />
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="h4 text-center">Information</div>
          <div class="row pv-lg">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
              <%= form_with(model: patient) do |form| %>
              <div class="row">
                <div class="col-md-6">
                  <%= form.label :firstname, style: "display: block" %> <%= form.text_field :firstname, class:'form-control' %>
                  <p style="color: red;"><%= patient.errors[:firstname]&.first if patient&.errors.any? %></p>
                </div>

                <div class="col-md-6">
                  <%= form.label :lastname, style: "display: block" %> <%= form.text_field :lastname, class:'form-control' %>
                  <p style="color: red;"><%= patient.errors[:lastname]&.first if patient&.errors.any? %></p>
                </div>

                <div class="col-md-6">
                  <%= form.label :mobile_no, style: "display: block" %> <%= form.text_field :mobile_no, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :email, style: "display: block" %> <%= form.text_field :email, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :diseases, style: "display: block" %> <%= form.text_field :diseases, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :appointment_date, style: "display: block" %> <%= form.datetime_field :appointment_date, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :reference_no, style: "display: block" %> <%= form.text_field :reference_no, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :pincode, style: "display: block" %> <%= form.number_field :pincode, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :address, style: "display: block" %> <%= form.text_area :address, class:'form-control' %>
                </div>

                <div class="col-md-6">
                  <%= form.label :special_remarks, style: "display: block" %> <%= form.text_area :special_remarks, class:'form-control' %>
                </div>
              </div>
              <br />
              <div>
                <%= form.submit "Submit", class: "btn btn-xs btn-success" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/_patient.html.erb
<div>
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Sr.No</th>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Mobile no</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
      <th scope="col">Pincode</th>
      <th scope="col">Appointment date</th>
      <th scope="col">Reference no</th>
      <th scope="col">Diseases</th>
      <th scope="col">Special remarks</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% patients.each_with_index do |record, i| %>
    <tr>
      <% i = i+1 %>
      <th scope="row"><%= i %></th>
      <td><%= record.firstname %></td>
      <td><%= record.lastname %></td>
      <td><%= record.mobile_no %></td>
      <td><%= record.email %></td>
      <td><%= record.address %></td>
      <td><%= record.pincode %></td>
      <td><%= record.appointment_date %></td>
      <td><%= record.reference_no %></td>
      <td><%= record.diseases %></td>
      <td><%= record.special_remarks %></td>
      <td style="
display: -webkit-inline-box;">
        <%= link_to patient_path(record.id) do %>
          <i class="fa fa-info-circle" aria-hidden="true" style="font-size:25px;color:green"></i>
        <% end %> 
        <%= link_to edit_patient_path(record) do %>
          <i class="fa fa-edit"aria-hidden="true" style="font-size:25px;color:blue"></i>
        <% end %>
        <%= button_to patient_path(record), :method => :delete, data: { confirm: 'Are you sure?' }, style:'border: none;' do %>
          <i class="fa fa-trash" aria-hidden="true" style="font-size:25px;color:red"></i>
        <% end %>
            </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/patients/_showpatient.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
<div id="<%= dom_id patient %>">
    <div class="container">
        <div class="team-single">
            <div class="row">
                <div class="col-lg-4 col-md-5 xs-margin-30px-bottom">
                    <div class="team-single-img">
                        <div class="pv-lg">
                            <img class="center-block img-responsive img-circle img-thumbnail thumb100" src="/assets/edit.jpg" alt="Contact" />
                        </div>
                    </div>
                    <div class="bg-light-gray padding-30px-all md-padding-25px-all sm-padding-20px-all text-center"></div>
                </div>

                <div class="col-lg-8 col-md-7">
                    <div class="team-single-text padding-50px-left sm-no-padding-left">
                        <center><h4 class="font-size38 sm-font-size32 xs-font-size30"><%= patient.firstname %> <%= patient.lastname %></h4></center>
                        <div class="contact-info-section margin-40px-tb">
                            <ul class="list-style9 no-margin">
                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fas fa-graduation-cap text-orange"></i>
                                            <strong class="margin-10px-left text-orange">Firstname:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.firstname %></p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="far fa-gem text-yellow"></i>
                                            <strong class="margin-10px-left text-yellow">Lastname:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.lastname %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fas fa-mobile-alt text-purple"></i>
                                            <strong class="margin-10px-left xs-margin-four-left text-purple">Mobile no:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.mobile_no %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fas fa-envelope text-pink"></i>
                                            <strong class="margin-10px-left xs-margin-four-left text-pink">Email:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.email %></p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fas fa-map-marker-alt text-green"></i>
                                            <strong class="margin-10px-left text-green">Address:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.address %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fa fa-map-pin text-lightred"></i>
                                            <strong class="margin-10px-left text-lightred">Pincode:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.pincode %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fa fa-calendar text-lightred"></i>
                                            <strong class="margin-10px-left text-lightred">Appointment date:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.appointment_date %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="far fa-file text-lightred"></i>
                                            <strong class="margin-10px-left text-lightred">Reference no:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.reference_no %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fa fa-h-square text-lightred"></i>
                                            <strong class="margin-10px-left text-lightred">Diseases:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.diseases %></p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="row">
                                        <div class="col-md-5 col-5">
                                            <i class="fa fa-comment text-lightred"></i>
                                            <strong class="margin-10px-left text-lightred">Special remarks:</strong>
                                        </div>
                                        <div class="col-md-7 col-7">
                                            <p><%= patient.special_remarks %></p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <h5 class="font-size24 sm-font-size22 xs-font-size20"></h5>
                        <center>
                            <div style="display: -webkit-inline-box;">
                                <%= link_to "Edit", edit_patient_path(@patient), class: "btn btn-xs btn-success"%> &nbsp;&nbsp;&nbsp; <%= link_to "Back to list", patients_path , class: "btn btn-xs btn-info" %> &nbsp;&nbsp;&nbsp; <%=
                                button_to @patient, :class => "btn btn-xs btn-light" , :method => :delete, data: { confirm: 'Are you sure?' }, style:'border: none;' do %>
                                <i class="fa fa-trash" aria-hidden="true" style="font-size: 25px; color: red;"></i>
                                <% end %>
                            </div>
                        </center>
                    </div>
                </div>

                <div class="col-md-12"></div>
            </div>
        </div>
    </div>
</div>

app/views/patients/edit.html.erb
<br />

<%= render "form", patient: @patient %>

<br />
<div class="container">
  <div style="display: -webkit-inline-box;">
    <%= link_to "Show this patient", @patient, class: "btn btn-xs btn-secondary"%> &nbsp;&nbsp;&nbsp; <%= link_to "Back to list", patients_path , class: "btn btn-xs btn-info" %> &nbsp;&nbsp;&nbsp;
  </div>
</div>

<br />
<br />

app/views/patients/index.html.erb
<div class="container-fluid h-custom">
  <br />
  <center><h3><%= !current_user.is_doctor ? "Receptionist" : "Doctor" %> Dashboard</h3></center>

  <p style="color: green;"><%= notice %></p>

  <div>
    <h3 style="float: left;">Patients List</h3>

    <%= link_to "Create New patient", new_patient_path, style:"float:right" , class: "btn btn-xs btn-success"%>
    <div>
      <div id="patients">
        <%= render "patient", patients: @patients %> <% if current_user.is_doctor %> <%= bar_chart Patient.group("DATE(appointment_date)").count %> <% end %>
      </div>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<br />
<center><h3>New patient</h3></center>

<%= render "form", patient: @patient %>

<br />

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green;"><%= notice %></p>

<%= render "showpatient", patient: @patient %>

<div style="display: -webkit-inline-box;"></div>